TODO: add MAScreenMat to CameraCube
cf. morse.sensors.camera.VideoCameraClass._setup_video_texture

Python script error from controller "Initialize#CONTR#3":
Traceback (most recent call last):
  File "/usr/local/lib/python3.1/dist-packages/morse/blender/main.py", line 398, in init
    init_ok = create_dictionaries()
  File "/usr/local/lib/python3.1/dist-packages/morse/blender/main.py", line 117, in create_dictionaries
    instance = create_instance (child, robot_instance)
  File "/usr/local/lib/python3.1/dist-packages/morse/blender/main.py", line 217, in create_instance
    instance = klass(obj, parent)
  File "/usr/local/lib/python3.1/dist-packages/morse/sensors/video_camera.py", line 21, in __init__
    super(self.__class__, self).__init__(obj, parent)
  File "/usr/local/lib/python3.1/dist-packages/morse/sensors/camera.py", line 46, in __init__
    self._setup_video_texture()
  File "/usr/local/lib/python3.1/dist-packages/morse/sensors/camera.py", line 88, in _setup_video_texture
    mat_id = VideoTexture.materialID(screen, material_name)
RuntimeError: VideoTexture.materialID(ob, string): Object doesn't have material with given name